CREATE TABLE  "FESTIVAL" 
   (	"COD_FESTIVAL" NUMBER(4,0) NOT NULL ENABLE, 
	"NOMBRE_FESTIV" VARCHAR2(30) NOT NULL ENABLE, 
	"CIUDAD" VARCHAR2(25) NOT NULL ENABLE, 
	"FECHA_CELEBRACION" DATE, 
	"FECHA_CREACION" DATE, 
	"CATEGORIA" NUMBER(2,0), 
	 CONSTRAINT "PK_FESTIVAL" PRIMARY KEY ("COD_FESTIVAL") ENABLE, 
	 CONSTRAINT "UK1_COD_FESTIVAL" UNIQUE ("NOMBRE_FESTIV") ENABLE
   ) ;

CREATE TABLE  "PAIS" 
   (	"COD_PAIS" NUMBER(3,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PAIS" PRIMARY KEY ("COD_PAIS") ENABLE
   ) ;

CREATE TABLE  "PAIS_PELICULA" 
   (	"COD_PELICULA" NUMBER(6,0) NOT NULL ENABLE, 
	"COD_PAIS" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PAIS_PELICULA" PRIMARY KEY ("COD_PELICULA", "COD_PAIS") ENABLE
   ) ;ALTER TABLE  "PAIS_PELICULA" ADD CONSTRAINT "FK_PAI_PEL_CON_PEL" FOREIGN KEY ("COD_PELICULA")
	  REFERENCES  "PELICULA" ("COD_PELICULA") ENABLE;ALTER TABLE  "PAIS_PELICULA" ADD CONSTRAINT "FK__PAI_PEL_CON_PAIS" FOREIGN KEY ("COD_PAIS")
	  REFERENCES  "PAIS" ("COD_PAIS") ENABLE;

CREATE TABLE  "PARTICIPACION" 
   (	"COD_FESTIVAL" NUMBER(4,0) NOT NULL ENABLE, 
	"COD_PELICULA" NUMBER(6,0) NOT NULL ENABLE, 
	"EDICION" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "PARTICIPACION_PK" PRIMARY KEY ("COD_FESTIVAL", "COD_PELICULA") ENABLE
   ) ;ALTER TABLE  "PARTICIPACION" ADD CONSTRAINT "FK_PAR_CON_FES" FOREIGN KEY ("COD_FESTIVAL")
	  REFERENCES  "FESTIVAL" ("COD_FESTIVAL") ENABLE;ALTER TABLE  "PARTICIPACION" ADD CONSTRAINT "FK_PAR_CON_PEL" FOREIGN KEY ("COD_PELICULA")
	  REFERENCES  "PELICULA" ("COD_PELICULA") ENABLE;

CREATE TABLE  "PELICULA" 
   (	"COD_PELICULA" NUMBER(6,0) NOT NULL ENABLE, 
	"TITULO" VARCHAR2(30) NOT NULL ENABLE, 
	"NUMERO_PRODUCCION" NUMBER(3,0) NOT NULL ENABLE, 
	"IDIOMA" VARCHAR2(20) NOT NULL ENABLE, 
	"GENERO" VARCHAR2(15) NOT NULL ENABLE, 
	"DURACION" NUMBER(6,0) NOT NULL ENABLE, 
	"FECHA_ESTRENO" DATE, 
	"SINOPSIS" VARCHAR2(1000) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PELICULA" PRIMARY KEY ("COD_PELICULA") ENABLE, 
	 CONSTRAINT "UK1_PELICULA" UNIQUE ("TITULO") ENABLE
   ) ;

CREATE TABLE  "PRODUCTORA" 
   (	"COD_PRODUCTORA" NUMBER(4,0) NOT NULL ENABLE, 
	"NOMBRE_PRODUCTORA" VARCHAR2(30) NOT NULL ENABLE, 
	"COD_PAIS" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PRODUCTORA" PRIMARY KEY ("COD_PRODUCTORA") ENABLE, 
	 CONSTRAINT "UK1_PRODUCTORA" UNIQUE ("NOMBRE_PRODUCTORA") ENABLE
   ) ;ALTER TABLE  "PRODUCTORA" ADD CONSTRAINT "FK_PRO_CON_PAIS" FOREIGN KEY ("COD_PAIS")
	  REFERENCES  "PAIS" ("COD_PAIS") ENABLE;

CREATE TABLE  "STAFF" 
   (	"COD_PERSONA" NUMBER(4,0), 
	"NOMBRE" VARCHAR2(20) NOT NULL ENABLE, 
	"APELLIDOS" VARCHAR2(30) NOT NULL ENABLE, 
	"FECHA_NACIMIENTO" DATE NOT NULL ENABLE, 
	"LUGAR_NACIMIENTO" VARCHAR2(30) NOT NULL ENABLE, 
	"COD_PAIS" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_STAFF" PRIMARY KEY ("COD_PERSONA") ENABLE
   ) ;ALTER TABLE  "STAFF" ADD CONSTRAINT "FK_STAFF_CON_PAIS" FOREIGN KEY ("COD_PAIS")
	  REFERENCES  "PAIS" ("COD_PAIS") ENABLE;

CREATE TABLE  "STAFFPELICULA" 
   (	"COD_PERSONA" NUMBER(6,0) NOT NULL ENABLE, 
	"COD_PELICULA" NUMBER(4,0) NOT NULL ENABLE, 
	"FUNCION" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PK_STAFFPELICULA" PRIMARY KEY ("COD_PERSONA", "COD_PELICULA", "FUNCION") ENABLE
   ) ;ALTER TABLE  "STAFFPELICULA" ADD CONSTRAINT "FK_STA_PEL_CON_PEL" FOREIGN KEY ("COD_PELICULA")
	  REFERENCES  "PELICULA" ("COD_PELICULA") ENABLE;ALTER TABLE  "STAFFPELICULA" ADD CONSTRAINT "FK_STA_PEL_CON_STA" FOREIGN KEY ("COD_PERSONA")
	  REFERENCES  "STAFF" ("COD_PERSONA") ENABLE;