CREATE TABLE PROVINCIAS(
    NOMBRE_PROV VARCHAR2(35) NOT NULL,
    PAIS VARCHAR2(30) NOT NULL,
    PIB NUMBER(11), 
    EXTENSION NUMBER(7),
        CHECK(PIB>0),
        CONSTRAINT CK_EXT CHECK (EXTENSION>0),
        CONSTRAINT PK_PROVINCIAS PRIMARY KEY (NOMBRE_PROV, PAIS)
)
/

CREATE TABLE PUEBLOS(
    COD_POBLACION NUMBER(6) NOT NULL,
    DESCRIPCION VARCHAR2(4) NOT NULL,
    PROVINCIA VARCHAR2(35),
    PAIS VARCHAR2(30),
    CATEGORIA NUMBER(1),
    FECHA_FUNDACION DATE CHECK (FECHA_FUNDACION < TO_DATE('01/01/2000', 'DD/MM/YYYY')),
    FECHA_INGRESO DATE,
        CONSTRAINT UK1_DESC UNIQUE (DESCRIPCION),
        CONSTRAINT CK_CATE CHECK(CATEGORIA IN(1,2,3))
)
/

INSERT INTO PROVINCIAS VALUES ('NUEVA SEGOVIA', 'NICARAGUA', 1245216, 1246)
/

INSERT INTO PROVINCIAS VALUES ('MARACAIBO', 'VENEZUELA', 21452341, 34415)
/

INSERT INTO PUEBLOS VALUES (21452, 'BONI', 'NUEVA SEGOVIA', 'NICARAGUA', 1, TO_DATE('01/01/1990', 'DD/MM/YYYY'), TO_DATE('05/02/2005', 'DD/MM/YYYY')
/

INSERT INTO PUEBLOS VALUES (12451, 'BARA', 'MARACAIBO', 'VENEZUELA', 2, TO_DATE('05/07/1995', 'DD/MM/YYYY'), TO_DATE('23/05/2007', 'DD/MM/YYYY')
/

ALTER TABLE PUEBLOS
    ADD (
    HABITANTES NUMBER(5) CHECK(HABITANTES BETWEEN 1000 AND 50000),
    CONSTRAINT PK_POB PRIMARY KEY (COD_POBLACION),
    CHECK (FECHA_INGRESO>FECHA_FUNDACION),
    CONSTRAINT FK1_PUE_PRO FOREIGN KEY (PROVINCIA, PAIS) REFERENCES PROVINCIAS(NOMBRE_PROV, PAIS)
)
/

ALTER TABLE PROVINCIAS
    MODIFY (
	PIB NUMBER(12) NOT NULL
	)
/

ALTER TABLE PUEBLOS
    DROP CONSTRAINT FK1_PUE_PRO
    DROP CONSTRAINT PK_POB
/

ALTER TABLE PROVINCIAS
    DROP CONSTRAINT PK_PROVINCIAS
/