CREATE TABLE PERSONAS(
    DNI VARCHAR2(9) NOT NULL,
    NOMBRE VARCHAR2(15) NOT NULL,
    APELLIDO1 VARCHAR2(25) NOT NULL,
    APELLIDO2 VARCHAR2(25) NOT NULL,
    DIRECCION VARCHAR2(35),
    POBLACION VARCHAR2(15),
    PROVINCIA VARCHAR2(30) CONSTRAINT CK_PROVINCIA CHECK(PROVINCIA IN('GIPUZKOA','BIZKAIA','ARABA')),
    TELEFONO VARCHAR2(9),
        CONSTRAINT PK_PERSONA PRIMARY KEY (DNI) 
)
/
INSERT INTO PERSONAS VALUES('54125674M', 'JON', 'IRAOLAGOITIA', 'GOÑI', 'KALE NAGUSIA', 'ORIO', 'GIPUZKOA', '943475496')
/
INSERT INTO PERSONAS VALUES('41527485L', 'MIKEL', 'TERES', 'AGOUES', 'SANTA MARINA', 'ZARAUTZ', 'GIPUZKOA', '943742516')
/
CREATE TABLE COCHES(
    MATRICULA VARCHAR2(8) NOT NULL,
    MODELO VARCHAR2(25),
    MARCA VARCHAR2(25),
    FECHA_MATRICULACION DATE CONSTRAINT CK_FECHA CHECK (FECHA_MATRICULACION > TO_DATE ('1/1/2016','DD/MM/YYYY')),
    DNI VARCHAR2(9) NOT NULL,
        CONSTRAINT PK_COCHES PRIMARY KEY (MATRICULA),
        CONSTRAINT FK1_COC_PER FOREIGN KEY (DNI) REFERENCES PERSONAS(DNI)
)
/
INSERT INTO COCHES VALUES('4433JXH', 'FOCUS', 'FORD', '7/6/2016', '41527485L')
/
INSERT INTO COCHES VALUES('5849JRZ', 'A4', 'AUDI', '9/3/2016', '54125674M')
/

CREATE TABLE APARTAMENTOS(
    COD_APARTAMENTO NUMBER(6) NOT NULL,
    CALLE VARCHAR2(25) NOT NULL,
    NUMERO NUMBER(3) NOT NULL,
    PISO NUMBER(2),
    PUERTA VARCHAR2(8),
    SUPERFICIE NUMBER(8,2) CONSTRAINT CK_SUPERFICIE CHECK (SUPERFICIE>0),
    DNI VARCHAR2(9) NOT NULL,
        CONSTRAINT PK_APARTAMENTOS PRIMARY KEY (COD_APARTAMENTO),
        CONSTRAINT FK1_APA_PER FOREIGN KEY (DNI) REFERENCES PERSONAS(DNI)
)
/
INSERT INTO APARTAMENTOS VALUES(1234, 'NAFARROA KALEA', 14, 4, '4I', 9472, '54125674M')
/
INSERT INTO APARTAMENTOS VALUES(2415, 'ARABA KALEA', 25, 3, '9A', 3241, '54125674M')
/