CREATE TABLE R_PROVINCIAS
(
	nom_provincia VARCHAR2(20) NOT NULL,
	prefijo VARCHAR2(20) ,
		CONSTRAINT PK_R_PROVINCIAS PRIMARY KEY (nom_provincia)
)
/
INSERT INTO R_PROVINCIAS VALUES ('GIPUZKOA', '943')
/
INSERT INTO R_PROVINCIAS VALUES ('MADRID', '91')

CREATE TABLE R_CIUDADES
(
    nom_ciudad VARCHAR2(25) NOT NULL,
    poblacion NUMBER(9),
    extension NUMBER(6) CONSTRAINT CK_R_CIUDADES CHECK (extension>0),
    nomprovincia VARCHAR2(20),
        CONSTRAINT PK_R_CIUDADES PRIMARY KEY (nom_ciudad)
        CONSTRAINT FK1_CIU_PRO(nomprovincia) REFERENCES R_PROVINCIAS(nom_provincia)
)
/
INSERT INTO R_CIUDADES VALUES('SAN SEBASTIAN', 300000, 652, 'GIPUZKOA')
/
INSERT INTO R_CIUDADES VALUES('MADRID', 5000000, 3045, 'MADRID')
/