CREATE TABLE MODULOS(
	Codigo_Mod NUMBER(2)NOT NULL,
	Descripcion VARCHAR2(20) NULL,
	CONSTRAINT MODULOS_PK PRIMARY KEY (Codigo_Mod),
	CONSTRAINT MODULOS_UK1 UNIQUE (Descripcion)
	);

CREATE TABLE ALUMNOS(
	Codigo_Alum NUMBER(3) NOT NULL,
	Usuario VARCHAR2(9) NOT NULL,
	Apellidos VARCHAR2(25) NOT NULL,
	Nombre VARCHAR2(15) NOT NULL,
	Direccion VARCHAR2(25) NULL,
	Poblacion VARCHAR2(15) NULL,
	Provincia VARCHAR2(30) NULL,
	Email VARCHAR2(40) NULL,
	Telefono VARCHAR2(9) NULL,
	
	CONSTRAINT ALUMNOS_PK PRIMARY KEY (Codigo_Alum),
	CONSTRAINT ALUMNOS_UK1 UNIQUE (Usuario)
	);

CREATE TABLE NOTAS(
	Codigo_Alum NUMBER(3) NOT NULL,
	Codigo_Mod NUMBER(2)NOT NULL,
	Nota NUMBER(3,2) NULL 
	
	CONSTRAINT NOTA_CK CHECK (Nota BETWEEN 0 AND 10),
	CONSTRAINT NOTAS_PK PRIMARY KEY (Codigo_Alum, Codigo_Mod),
	CONSTRAINT NOT_ALU_FK1 FOREIGN KEY (Codigo_Alum) REFERENCES ALUMNOS (Codigo_Alum),
	--ON DELETE CASCADE,
	CONSTRAINT NOT_MOD_FK1 FOREIGN KEY (Codigo_Mod) REFERENCES MODULOS (Codigo_Mod)
	--ON DELETE CASCADE
);