-- ESTO ES UN EJEMPLO DE INSERT EN SQL
-- CEUTA ENTRE COMILLAS IMPORTANTE
-- SYSDATE NOS DA LA FECHA EXACTA DEL ORDENADOR
INSERT INTO PROVINCIAS(
    VALUES(51, 'CEUTA', SYSDATE) --TO_DATE('1/1/1900', 'DD/MM/YYYY'))
    -- SYSDATE NOS COGE LA FECHA DEL MOMENTO SI NO TO_DATE
    --TO_CHAR(SYSDATE, 'DD/MM') PARA PASAR LA FECHA A STRING
    -- TRUNC(SYSDATE)

     
)