CREATE TABLE COPI_PROVINCIAS
AS SELECT *
    FROM PROVINCIAS
/
    
INSERT INTO COPIAPROVINCIAS(PROVINCIA)
SELECT PROVINCIAS
FROM PROVINCIAS
WHERE MOD(PREFIJO, 2) = 0;
/

DELET FROM PROVINCIAS
WHERE PROVINCIA NOT IN(SELECT PROVINCIA
                       FROM CLIENTES
                       WHERE PROVINCIA IS NOT NULL)
/

UPDATE PROVINCIAS
SET PREFIJO = 0, DESCRIPCION=NULL
WHERE MOD(PREFIJO, 2) = 0
/

UPDATE CLIENTES
SET TOTAL_FACTURA = (SELECT SUM(PRECIO*CANTIDAD)
                     FROM LINEAS, ALBARANES
                     WHERE LINEAS.ALBARAN = ALBARANES.ALBARAN
                       AND ALBARANES.CLIENTE = CLIENTES.CLIENTE)
/
