CREATE TABLE COPI_PROVINCIAS
AS SELECT *
    FROM PROVINCIAS
/
    
INSET INTO COPIAPROVINCIAS(PROVINCIA)
SELECT PROVINCIAS
FROM PROVINCIAS
WHERE MOD(PREFIJO, 2) = 0;
/

DELET FROM PROVINCIAS
WHERE PROVINCIA NOT IN(SELECT PROVINCIA
                       FROM CLIENTES
                       WHERE PROVINCIA IS NOT NULL)
/

UPDATE PROVINCIAS
SET PREFIJO = 0, DESCRIPCION=NULL
WHERE MOD(PREFIJO, 2) = 0
/
