CREATE TABLE PROVINCIAS
	(codigo NUMBER(3) NOT NULL,
	NOMBRE VARCHAR2(20) NOT NULL,
	PAIS VARCHAR2(25) DEFAULT 'SPAIN' NOT NULL);

CREATE TABLE CLIENTES
	(COD_CLI NUMBER(3) NOT NULL,
	EMPRESA VARCHAR2(25) NOT NULL,
	PROVINCIA NUMBER(3),
		CONSTRAINT FK_CLI_PRO
