CREATE TABLE FABRICANTES(
	NOMBRE_FABRICANTE VARCHAR2(30),
	PAIS VARCHAR2(15),
		CONSTRAINT PK_FAB PRIMARY KEY (NOMBRE_FABRICANTE),
		CONSTRAINT CK1_FAB CHECK(NOMBRE_FABRICANTE=UPPER(NOMBRE_FABRICANTE))
)
/


CREATE TABLE MANUFACTURA(
	MARCA VARCHAR2(20) NOT NULL,
	NOMBRE_FABRICANTE VARCHAR2(30),
	CARTON NUMBER(2),
	EMBALAJE NUMBER(2),
		CONSTRAINT PK_MAN PRIMARY KEY (MARCA),
		CONSTRAINT CK1_MAN CHECK(MARCA=UPPER(MARCA)),
		CONSTRAINT FK1_MAN_FAB FOREIGN KEY (NOMBRE_FABRICANTE) REFERENCES FABRICANTES(NOMBRE_FABRICANTE),
		CHECK(CARTON>0),
		CONSTRAINT CK2_EMBALAJE CHECK(EMBALAJE>0)		
)
/

CREATE TABLE CIGARRILLOS(
	MARCA VARCHAR2(20) NOT NULL,
	FILTRO VARCHAR2(1) NOT NULL,
	COLOR VARCHAR2(1) NOT NULL,
	CLASE VARCHAR2(20) NOT NULL,
	MENTOL VARCHAR2(1) NOT NULL,
	NICOTINA NUMBER(3,1),
	ALQUITRAN NUMBER(6,2),
	PRECIO_VENTA NUMBER(3) DEFAULT (0),
		CONSTRAINT FK1_CIG_MAN FOREIGN KEY (MARCA) REFERENCES MANUFACTURA(MARCA),
		CONSTRAINT CK1_FILTRO CHECK(UPPER(FILTRO) IN('S','N')),
		CONSTRAINT CK2_COLOR CHECK(UPPER(COLOR) IN('R','N')),
		CONSTRAINT CK3_CLASE CHECK(UPPER(CLASE) IN('LIGHT','NORMAL'))
)
/

CREATE TABLE ESTANCOS(
	NIF_ESTANCO VARCHAR2(12) NOT NULL,
	EXPENDEDURIA NUMBER(4) NOT NULL,
	CP_ESTANCO NUMBER(5) NOT NULL,
	NOMBRES_ESTANCO VARCHAR2(30) NOT NULL,
	DIRECCION_ESTANCO VARCHAR2(30),
	LOCALIDAD_ESTANCO VARCHAR2(15),
		CONSTRAINT PK_EST PRIMARY KEY (NIF_ESTANCO),
		CHECK (NOMBRES_ESTANCO=UPPER(NOMBRES_ESTANCO))
)
/

INSERT INTO FABRICANTES VALUES('MARLBORO S.L.', 'ESTADOS UNIDOS')
/

INSERT INTO FABRICANTES VALUES('CHESTER S.A.', 'ITALIA')
/

INSERT INTO MANUFACTURA VALUES('MARLBORO', 'MARLBORO S.L.', 20, 3)
/

INSERT INTO MANUFACTURA VALUES('CHESTER', 'CHESTER S.A.', 17, 2)
/

INSERT INTO  CIGARRILLOS VALUES('CHESTER', 'S', 'R', 'LIGHT', 'N', 12, 25, 25)
/

INSERT INTO CIGARRILLOS VALUES('MARLBORO', 'S', 'N', 'NORMAL', 'S', 12.5, 12, 5)
/

INSERT INTO ESTANCOS VALUES('41524151L', 2435, 20830, 'ESTANCO ISABEL', 'KALE NAGUSIA', 'ERREZIL')
/

INSERT INTO ESTANCOS VALUES('14287496S', 1214, 20894, 'ALTZAPORRU', 'FORUEN KALEA', 'ORIO')
/

ALTER TABLE CIGARRILLOS
	ADD(
		PRECIO_COSTO NUMBER(3),
		CHECK(PRECIO_COSTO <= PRECIO_VENTA),
		CONSTRAINT PK_CIG PRIMARY KEY (MARCA, FILTRO, COLOR, CLASE, MENTOL),
		CHECK(MENTOL IN('S','N'))
	)
	
	MODIFY(
		NICOTINA NUMBER(5) NOT NULL, -- CON ESTO NOS DA EL MENSAJE column to be modified must be empty to decrease precision or scale
		ALQUITRAN NUMBER(4,2) DEFAULT(5) NOT NULL
	)
/

ALTER TABLE ESTANCOS
	ADD(
		PROVINCIA_ESTANCO VARCHAR2(9),
		CHECK(PROVINCIA_ESTANCO IN('BARCELONA', 'GIPUZKOA')),
		CONSTRAINT UK1_EST UNIQUE (EXPENDEDURIA, CP_ESTANCO)
	)
	
	MODIFY(
		NOMBRES_ESTANCO VARCHAR2(35),
	)
/

ALTER TABLE MANUFACTURA
	DROP CONSTRAINT FK1_MAN_FAB
	DROP CONSTRAINT SYS_C008027
/

